name: Build

on:
  push:
    branches: [ "dev", "master" ]
  pull_request:
    branches: [ "dev", "master" ]
  pull_request_target:
    types:
      - opened
    branches:
      - '*/*'

permissions:
  pull-requests: write
  contents: read

jobs:
  prettier_lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
    - run: yarn --immutable
    - run: yarn prettier:check
    - run: yarn lint

  unit_test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v3
    - uses: browser-actions/setup-chrome@latest
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
    - run: yarn --immutable
    - run: yarn coverage
    - name: Upload to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        directory: ./coverage/
        files: clover.xml
        flags: unittests
        name: codecov-report
        verbose: true

  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
    - run: yarn --immutable
    - run: yarn build
    - name: Save dist
      uses: actions/upload-artifact@v3
      with:
        name: dist
        if-no-files-found: error
        path: dist

  # cypress-run:
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       node-version: [20.x]
  #   needs: build
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3
  #     - name: Use Node.js ${{ matrix.node-version }}
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: ${{ matrix.node-version }}
  #         cache: 'yarn'

  #     - name: Cypress install
  #       uses: cypress-io/github-action@v6
  #       with:
  #         runTests: false

  #     - name: Download the build folder
  #       uses: actions/download-artifact@v3
  #       with:
  #         name: dist
  #         path: dist

  #     - name: Cypress run
  #       uses: cypress-io/github-action@v6
  #       with:
  #         start: yarn start:cytest && yarn cy:run
  #         wait-on: ${{ matrix.node-version == 20 && 'http://[::1]:3000' || 'http://localhost:3000' }}
  #         wait-on-timeout: 300
  #         browser: chrome

      # - name: Upload coverage to Codecov
      #   uses: codecov/codecov-action@v3
      #   with:
      #     directory: cypress-coverage
      #     files: clover.xml
      #     flags: uitests
      #     name: codecov-report
      #     verbose: true